server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/et2512-dishes
    username: root
    password: etoak

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.etoak
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl